### ISSUE TITLE
Exclude e2e from audit logs

### ISSUE THREAD

**Issue by sethvargo** [google/exposure-notifications-verification-server#1153]
The system event log is quite littered with actions by the e2e-runner, making it _incredibly_ difficult to discern actual behavior for the data. Should we exclude the e2e-runner from events/audits? We can either prevent creating them or prevent showing them.

@whaught @chaodaiG thoughts?

<img width="743" alt="screenshot-20201120-100808@2x" src="https://user-images.githubusercontent.com/408570/99815433-4c0c0e00-2b18-11eb-96eb-dc486570b218.png">

**Comment by chaodaiG** [comment]
Agree that these should not be shown, hiding them is preferable to me

**Comment by whaught** [comment]
I don't want to skip logging per-se (I don't want there to exist a way to bypass), but I think the ability to mark and AppId as 'test' and have a static Auditable SystemTest instead of just System. Then we can implement a filter in the logs to not show these by default with a checkbox to show them.

Thoughts?

**Comment by sethvargo** [comment]
I think that's fine, but I'm curious why add `IsTest` to auditable? We can just filter audits where the principle is SystemTest (which feels cleaner)

**Comment by whaught** [comment]
Because we can use SystemTest for the things where System was the auditable, but parts of the the test eg. https://github.com/google/exposure-notifications-verification-server/blob/d2c677772dd08b06c1f7e61506370cae2218c28c/pkg/clients/e2e.go#L93
Also are taking actions that will go to the realm log. This allows us to filter any kind of test. If PWC wants to build external tests in the future, this all makes it simple for anything to be marked as test.

**Comment by sethvargo** [comment]
My pref would be to just use SystemTest for now. We could also build a system-admin-only portal to generate API keys that are tagged as SystemTest that PWC could use for their testing.
