### ISSUE TITLE
iOS / ENX redirect

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#1463]
### TL;DR

We need a new setting for iOS where a custom app and ENX co-exist.

That setting is to not redirect to the app store if a redirect request reaches the redirect server AND there is iOS metadata.

If EN Express is enabled && there is an iOS app, we should still build the ens:// URL because if the custom app was installed, it would have grabbed the link.

**Comment by sethvargo** [comment]
Added in #1466. FWIW, I think we have a bug in the current implementation in that there's no checking to see if ENX is enabled.

If the user provides a valid user agent for iOS or Android and there's no app registered, the current behavior is to redirect to the `ens://` link, even if the realm doesn't have enx enabled. That's fixed in the PR too.
