### ISSUE TITLE
0.36.0 release doesn't have changes provided in the release notes

### ISSUE THREAD

**Issue by Apisov** [google/exposure-notifications-verification-server#2214]
### TL;DR
0.36.0 release doesn't have all changes from the `main` branch. 

**Expected behavior**
A release branch contains all the states changes in the release notes.

**Observed behavior**
Last commit of the 0.36.0 release is the same as in the 0.35.0 version.

**Comment by sethvargo** [comment]
Hi @Apisov 

Thank you for opening an issue. I'm not sure what you mean. The [0.35.0 release](https://github.com/google/exposure-notifications-verification-server/releases/tag/v0.35.0) is tagged against 745ce49. The [0.36.0 release](https://github.com/google/exposure-notifications-verification-server/releases/tag/v0.36.0) is tagged against f5c9507. 

Is there a specific change that you believe is missing? Please note that our release notes do not correspond 1:1 with commit's or PRs, since some are only for internal cleanup and are not relevant for server operators. The target audience for release notes are server operators.

**Comment by mikehelmick** [comment]
Tag diff -> https://github.com/google/exposure-notifications-verification-server/compare/v0.35.0...v0.36.0

between 36 and 35 releases

**Comment by mikehelmick** [comment]
when I look through this view, https://github.com/google/exposure-notifications-verification-server/commits/v0.36.0

the commits seem wrong... taking a look at the tree on a clone...

**Comment by mikehelmick** [comment]
created a 0.36.1 that contains the intended v0.36.0 commits. Release branch updated

![image](https://user-images.githubusercontent.com/92319/131756945-9ac6dcf6-eca2-42b4-a28a-e36eca7655e9.png)
