### ISSUE TITLE
Bulk user creation

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#517]
Allow realms to bulk-create user accounts.

Possibly paste in or upload a csv

/kind enhancement

**Comment by whaught** [comment]
/close

Closing this for now. It's implemented, but I want to wait for feedback from users on the experience before going further. It uses html5 file reader to do the batching which is nice because we both want to create the user and send the email (the latter happens from the client in JS from firebase) which means we can't process all server-side. Doing it in small chunks prevents a weird fail-in-the-middle where the users are created but no invites are sent yet.

That said html5 may not work on super old browsers, for example.
