### ISSUE TITLE
Cannot deploy e2e-runner

### ISSUE THREAD

**Issue by sethvargo** [google/exposure-notifications-verification-server#818]
The e2e-runner in prod fails to deploy with:

```text
"error trying to create a new Admin API Key: failed to save API key: pq: duplicate key value violates unique constraint "realm_apikey_name""
```

This is an intermittent failure, but blocks deployment.

/cc @chaodaiG

**Comment by chaodaiG** [comment]
There are two DB columns that have this constraint: `RealmID ` and `Name`. Since `Name` is generated by [crypto/rand](https://github.com/google/exposure-notifications-verification-server/blob/c47a42cf4b63d530b9637e1991c616e98bcdbe15/cmd/e2e-runner/main.go#L120) it's highly unlikely innocent based on how often the problem appeared

Link: https://github.com/google/exposure-notifications-verification-server/blob/3b3e584551cd772198137a9f7168797ea7504bc6/pkg/database/authorized_app.go#L67

**Comment by chaodaiG** [comment]
I can take a stab fixing this later today, if my hypothesis is correct

**Comment by chaodaiG** [comment]
The hypothesis above was incorrect, the collision was still on `Name`. It's likely due to the fact that the random suffix was created with an int below 10000, and without cleanup the chance of collision increase over time
