### ISSUE TITLE
Better logging

### ISSUE THREAD

**Issue by jendakol** [google/exposure-notifications-verification-server#946]
Hello,
we are one of the users of the referential Verification (and Key) server. We're quite often facing problems that our users are unable to send us their keys and, reciprocally, we're unable to help him because we don't see almost anything useful in logs.

Imagine a case: user enters a verification code that was issued for him a few minutes ago and the upload fails, seeing "invalid code" message on the device. The problem is that even with our traffic (1.3M devices), we're often unable to find relevant lines in the log and even if we find them, we see nothing more than e.g. "verification code expired" (in a case when this should not be possible as the code was young enough).

I'd like to suggest you revise the logging in the whole Verification server (and especially the `verifyapi`) to show more useful information. I think it should be optional so no one would be forced to see that if he doesn't want to - logging level could solve that. I've noticed DEBUG logging level is not used in the Verification server almost at all...

An additional thing I'd love to see is to introduce a request tracing. A minimal form is that a reader of logs should be able to connect logging entries together to a single request to see the flow. An ideal case would be to have support for e.g. [opentracing](https://github.com/opentracing/opentracing-go) so the device would generate a pseudo-unique request ID for every request and this ID would be visible together with an error message to the user so he could report the ID to the support. Things would get much easier then... (and it still shouldn't jeopardize user privacy)

Please let me know what do you think about this. I'm willing to participate in the implementation if you'd like to. This is a real support-pain for us.

**Comment by sethvargo** [comment]
Are you running with debug logs on? Debug logging is off by default. You can enable it with  `LOG_DEBUG=true`.

Due to the privacy-preserving nature of the system, I don't think we want to enable that level of tracing.

**Comment by jendakol** [comment]
Yes, we tried to enable debug logging but nothing was changed in our specific case. I spent 2 hours reading the code yesterday and there is no verify-related logging there...

What kind/level of tracing is out of the discussion for you?

**Comment by mikehelmick** [comment]
Hello - 

For the verification server, we have a set of well documented error codes
https://github.com/google/exposure-notifications-verification-server/blob/main/docs/api.md#api-methods

These are meant to indicate back to the client software the nature of the failure. code_invalid for example indicates the code is indeed invalid (Doesn't exist at the database) OR was already used.

The most likely case in what you described is a mistyped code.
We highly recommend delivering codes via SMS so that copy/paste can eliminate this class of errors.

We will look into adding some additional debug logging through the device side API flows, but need to do so correctly.

As Seth mentioned, I don't think we should add end to end tracing due to the privacy preserving nature of the system. We do not want trace spans to be identified across both servers for sure.

**Comment by jendakol** [comment]
Hi,

we're well aware of the error codes, it would be an insane hell without them :-) Still, when the error is `code_expired`, it's 5 minutes old and its validity is 1h, something is very wrong and we're blind. We keep sending the user (I mean, this has indeed happened, multiple times!) new codes it doesn't help. Hence the need for much more thorough logging...

Spans across both servers would be of course great but that's not needed. Single-request trace ID would be enough - as I said, it's about being able to find a request from a specific user in the logs **when he tells us the trace id** - so no privacy is in the game here, he actually _wants_ us to find his request to debug it.
